### ISSUE TITLE
Tracking: Tooling improvements

### ISSUE THREAD

**Issue by LordGrimmauld** [LordGrimmauld/apparmor-dev#1]
- Github
  - [ ] Automatic flake updates
  - [ ] Automatic apparmor git version updates
  - [x] Running flake checks using https://github.com/nix-community/nix-github-actions
- Dev Shells
  - [ ] Shell for libapparmor
  - [ ] Shell for parser (depends on lib)
  - [ ] Shell for bin-utils  (depends on lib, and probably on parser)
  - [ ] Shell for everything else
- VM Tests
  - [x] Run apparmor nixos test
  - [x] Run regression test in a VM (needs a vm because it depends on running apparmor in the kernel)
- Overlays
  - [x] Provide overlays to override apparmor packages in nixpkgs with their flake alpha equivalent
  - [x] Provide NixOS module loading the overlays
- Functionality
  - [x] Fix flake eval for ~~`aarch64-linux`~~ cross-system without emulation (remove IFD)
  - [ ] Fix bad test cases
    - [ ] attach_disconnected
    - [ ] capabilities
    - [ ] unix_socket_pathname
    - [x] e2e (assumes caching enabled)
  - [x] enable make checks
  - [x] add meta.mainProgram to parser package
